import type { NextPage } from 'next'
import useSWR from 'swr'
import Head from 'next/head'
import Script from 'next/script'
import { toast } from 'react-toastify'
import HttpCodeBadge from '../components/HttpCodeBadge'

type RequestLog = {
  date: string
  path: string
  method: string
  status_code: number
  response_time: number
}

const Home: NextPage = () => {
  const { data, isValidating, mutate } = useSWR<RequestLog[]>('api/requests')

  const onGenerateNewRequest = () => {
    const requestOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    }
    fetch('api/users', requestOptions)
      .then((response) => response.json())
      .then((data) => {
        if (data.error) {
          toast.error(data.error)
        } else {
          toast.success('Created a request')
          mutate()
        }
      })
  }

  if (isValidating) {
    return <div className="space-y-6">Loading...</div>
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        onClick={onGenerateNewRequest}
        className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
      >
        <span className="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
          Generate a request
        </span>
      </button>

      <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" className="py-3 px-6">
              Date (utc)
            </th>
            <th>Path</th>
            <th>Status</th>
            <th>Response Time (s)</th>
          </tr>
        </thead>
        <tbody>
          {data &&
            data.map((request: RequestLog) => {
              return (
                <tr
                  key={''}
                  className="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
                >
                  <td>{request.date}</td>
                  <td>
                    <code>{request.path}</code>
                  </td>
                  <td>
                    <HttpCodeBadge code={request.status_code} />
                  </td>
                  <td>{request.response_time}</td>
                </tr>
              )
            })}
        </tbody>
      </table>

      <Script
        defer
        src="https://unpkg.com/@tinybirdco/flock.js"
        data-host="https://api.us-east.tinybird.co"
        data-token="p.eyJ1IjogImNjZWRjOWUyLTcxZmQtNDQ4Yy1hZmRkLTQzYTI5ZTUyOTYwZCIsICJpZCI6ICI1OGQyY2E1Ni0xYTkxLTQ0YWYtOWNiMy0zMmUwYTcwNGE1NzYifQ.UyJ9OfLWwsf7Ks0_UfS4PmT0wIB9_yw3qxWPnuFbmXo"
      />
      <footer></footer>
    </div>
  )
}

export default Home
